openapi: 3.0.0
info:
  title: Sync API
  version: 1.0.0
paths:
  /getPassword/{username}:
    get:
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A hashed password
          content:
            application/json:
              schema:
                type: string
  /getUserID/{username}:
    get:
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A user ID
          content:
            application/json:
              schema:
                type: integer
  /sendFile/{userID}:
    post:
      parameters:
        - name: userID
          in: path
          required: true
          schema:
            type: integer
        - name: fileName
          in: query
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: File uploaded successfully
  /getFile/{userID}/{entryID}:
    get:
      parameters:
        - name: userID
          in: path
          required: true
          schema:
            type: integer
        - name: entryID
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: File retrieved successfully
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
  /getData/{table}/{userID}/{entryID}:
    get:
      parameters:
        - name: table
          in: path
          required: true
          schema:
            type: string
        - name: userID
          in: path
          required: true
          schema:
            type: integer
        - name: entryID
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Data retrieved successfully
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: string
  /addData/{table}/{userID}/{entryID}:
    post:
      parameters:
        - name: table
          in: path
          required: true
          schema:
            type: string
        - name: userID
          in: path
          required: true
          schema:
            type: integer
        - name: entryID
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: string
      responses:
        '200':
          description: Data added successfully
  /updateData/{table}/{userID}/{entryID}:
    put:
      parameters:
        - name: table
          in: path
          required: true
          schema:
            type: string
        - name: userID
          in: path
          required: true
          schema:
            type: integer
        - name: entryID
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: string
      responses:
        '200':
          description: Data updated successfully
  /deleteData/{table}/{userID}/{entryID}:
    delete:
      parameters:
        - name: table
          in: path
          required: true
          schema:
            type: string
        - name: userID
          in: path
          required: true
          schema:
            type: integer
        - name: entryID
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Data deleted successfully
  /getAllData/{table}/{userID}:
    get:
      parameters:
        - name: table
          in: path
          required: true
          schema:
            type: string
        - name: userID
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: All data retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  additionalProperties:
                    type: string 
  /register:
      post:
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  password:
                    type: string
        responses:
          '200':
            description: User registered successfully
  /login:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  userID:
                    type: integer