openapi: 3.0.0
info:
  title: Sync API
  version: 1.0.0
paths:
  /getPassword/{username}:
    get:
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A hashed password
          content:
            application/json:
              schema:
                type: string
  /getUserID/{username}:
    get:
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A user ID
          content:
            application/json:
              schema:
                type: integer
  /sendFile/{userID}:
    post:
      parameters:
        - name: userID
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: File uploaded successfully
  /getData/{table}/{userID}:
    get:
      parameters:
        - name: table
          in: path
          required: true
          schema:
            type: string
        - name: userID
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Data retrieved successfully
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: string
  /addData/{table}/{userID}:
    post:
      parameters:
        - name: table
          in: path
          required: true
          schema:
            type: string
        - name: userID
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: string
      responses:
        '200':
          description: Data added successfully
  /updateData/{table}/{userID}/{id}:
    put:
      parameters:
        - name: table
          in: path
          required: true
          schema:
            type: string
        - name: userID
          in: path
          required: true
          schema:
            type: integer
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: string
      responses:
        '200':
          description: Data updated successfully
  /deleteData/{table}/{userID}/{id}:
    delete:
      parameters:
        - name: table
          in: path
          required: true
          schema:
            type: string
        - name: userID
          in: path
          required: true
          schema:
            type: integer
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Data deleted successfully
  /getAllData/{table}/{userID}:
    get:
      parameters:
        - name: table
          in: path
          required: true
          schema:
            type: string
        - name: userID
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: All data retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  additionalProperties:
                    type: string
  /clearData/{table}/{userID}:
    delete:
      parameters:
        - name: table
          in: path
          required: true
          schema:
            type: string
        - name: userID
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Data cleared successfully
